language: python

python:
  - "3.6"
node_js:
  - ""

cache: pip

install:
    - pip install -r python_client/requirements.txt
    - pip install -r test/requirements.txt
    - pip install -r server/backbone_server/REQUIREMENTS
    - pip install -r upload/requirements.txt
    - pip install python-coveralls
    - npm install -g @angular/cli
    - (cd client/sims-backbone;npm install)

script:
  - (export LOCAL_TEST=1;pytest --cov=backbone_server --cov-report term-missing -v test/)
  - psql -c "DELETE FROM attrs;" -U ${POSTGRES_USER} ${POSTGRES_DB}
  - psql -c "DELETE FROM studies;" -U ${POSTGRES_USER} ${POSTGRES_DB}
  - psql -c "DELETE FROM taxonomies WHERE id=7227;" -U ${POSTGRES_USER} ${POSTGRES_DB}
  - (cd upload/test;LOCAL_TEST=1 ./run.sh)
  - (cd client/sims-backbone;xvfb-run -a ng test --no-watch --no-progress --browsers=ChromeNoSandbox --code-coverage)
    #  - (cd client/sims-backbone;xvfb-run -a ng e2e --no-progress --config=protractor-ci.conf.js)

services:
    - postgresql

before_install:
    - nvm install 8
    - ./generate.sh noauth

before_script:
    - export POSTGRES_USER="postgres"
    - export POSTGRES_DB="backbone_service"
    - psql -c "create database ${POSTGRES_DB};" -U ${POSTGRES_USER}
    - psql -U ${POSTGRES_USER} -c "create extension postgis" ${POSTGRES_DB}
    - psql -c "\i database/backbone_service.psql;" -U ${POSTGRES_USER} ${POSTGRES_DB}
    - psql -c "ALTER DATABASE ${POSTGRES_DB} SET search_path=public, ${POSTGRES_DB}, contrib;" -U postgres
    - psql -c "SELECT postgis_full_version();" -U ${POSTGRES_USER} ${POSTGRES_DB}
    - psql -c "\copy countries (English, French, alpha2, alpha3, numeric_code) FROM './database/country_codes.tsv' DELIMITER E'\t'  HEADER CSV; " -U ${POSTGRES_USER} ${POSTGRES_DB}
    - psql -c "\copy taxonomies (id, rank, name) FROM './database/taxa.tsv' DELIMITER E'\t'  HEADER CSV;" -U ${POSTGRES_USER} ${POSTGRES_DB}
    - export PYTHONPATH=$(pwd)/python_client:$(pwd)/server:$(pwd)/server/bb_server
    - export REMOTE_HOST_URL=http://localhost:8080/v1

after_success:
  - coveralls

addons:
    postgresql: "9.6"
    apt:
      packages:
        - postgresql-9.6-postgis-2.3
    chrome: stable
