#!/bin/bash

test -f environment_local && source environment_local
test -f ${INPUT1_STAGING_DIR}/import/environment && source ${INPUT1_STAGING_DIR}/import/environment

OUTFILE=${OUTPUT1_STAGING_DIR}/import_$(date +%Y-%m-%d-%H%M%S).log
export PYTHONPATH=$(pwd)/../python_client:$(pwd)/../server:$(pwd)/../server/bb_server
# Redirect stdout ( > ) into a named pipe ( >() ) running "tee"
exec &> >(tee -i ${OUTFILE})

echo ${INPUT1_STAGING_DIR}
echo ${ARCHIVE_DIR}

ARCHIVE_DIR=${OUTPUT1_STAGING_DIR}/archive

shopt -s nullglob
for i in ${INPUT1_STAGING_DIR}/import/roma/*
do
    if [ $i != "_dummy" ]
    then
        test -d ${ARCHIVE_DIR}/roma || mkdir -p ${ARCHIVE_DIR}/roma
        INSTANCE=$(basename ${i} | awk -F_ '{print $1}')
        ROMA_LOG=${OUTPUT1_STAGING_DIR}/${INSTANCE}_$(date +%Y-%m-%d-%H%M%S).log
        python3 upload_roma.py ${IMPORT_CONFIG} $i 2>&1 | tee -i ${ROMA_LOG}
        if [ -s ${ROMA_LOG} ]
        then
            python3 upload_log.py ${CMIS_CONFIG} ${ENVIRON} ${ROMA_LOG}
        fi
        mv $i ${ARCHIVE_DIR}/roma/$(basename ${i})
    fi
done
METADATA_LOG=${OUTPUT1_STAGING_DIR}/metadata_$(date +%Y-%m-%d-%H%M%S).log
python3 set_taxa.py ${IMPORT_CONFIG} | tee -i ${METADATA_LOG}
python3 set_studies.py ${IMPORT_CONFIG} ${CMIS_CONFIG} | tee -i ${METADATA_LOG}
