./run.sh oxford.csv oxford.json
./run.sh vw_vrpipe.txt vw_vrpipe.json
./run.sh pf_6_metadata.txt pf_6_metadata.json
./run.sh ./pv_3.denormalized.txt pv_3_sanger_source_code_metadata.json
./run.sh ./manage_sites.denormalized.txt denorm_manage_sites.json
./run.sh pv_3_broad_metadata.txt pv_3_broad_metadata.json
./run.sh genre.dump_samples.tsv genre.json
./run.sh spotmalaria.dump_samples.tsv spotmalaria.dump_samples.json
./run.sh vivax.dump_samples.tsv vivax.json
./run.sh vobs.dump_samples.tsv vobs.json
./run.sh ag1000g.samples.meta.txt ag1000g.json
