#!/bin/bash
source upload-env/bin/activate
export PYTHONPATH=$(pwd)/../python_client:$(pwd)/../server:$(pwd)/../server/bb_server
export TOKEN_URL=https://sso3.malariagen.net/sso/oauth2.0/accessToken
export IMPORT_CONFIG=config_dev.json
